name: Run Test

on: [push]

jobs:
  run-test:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: git pull submodules
        run: git submodule update --init --recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TEST=ON

      - name: Build C++ and Run C++ Tests
        run: |
          cd build
          make
          ./run-test

      - name: Install Python Dependencies and Package
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          python setup.py develop

      - name: Run Python Tests
        run: |
          pytest
